# You may use unicode characters if you'd like. If you are. Please add -Dfile.encoding=UTF-8 to your start up script to ensure it saves properly.
# Using placeholders is not recommended because it is still in beta and being worked on. Make sure to download placeholder expansion if you use it though.
# Like you can use /papi ecloud download Player then you can use the placeholder %player_name%, but as I said, enabling placeholders is not recommended.
# If you do not know how to use webhooks please read the plugin post there is a quick explanation. Webhook logs all the chat messages. Adminchat, devchat and sc.
staffchat:
  error: '&cYou are not allowed to execute this command. Contact a server administrator
    if you believe this is an error.'
  disable-off: '&3You have disabled StaffChat!'
  disable-on: '&3You have enabled StaffChat!'
  toggle-on: '&3You will now send messages in &eStaffChat&3!'
  toggle-off: '&3You will no longer send messages in &eStaffChat&3!'
  header: '&8[&eStaffChat&8]&f '
  placeholder:
    name: '%placeholderyouwant%'
  discordwebhook:
    enabled: false
    webhook: INSERT-WEBHOOK-HERE
    webhookusername: StaffChat Logs
    footer: New Staff Chat message
    footericon: https://i.imgur.com/frdEAle.png
adminchat:
  error: '&cYou are not allowed to execute this command. Contact a server administrator
    if you believe this is an error.'
  disable-off: '&3You disabled Admin Chat!'
  disable-on: '&3You enabled Admin Chat'
  toggle-on: '&3You will now send messages in &cAdminChat&3!'
  toggle-off: '&3You will no longer send messages in &cAdminChat&3!'
  header: '&8[&cAdminChat&8]&f '
  placeholder:
    name: '%placeholderyouwant'
  discordwebhook:
    enabled: false
    webhook: INSERT-WEBHOOK-HERE
    webhookusername: StaffChat Logs
    footer: New Staff Chat message
    footericon: https://i.imgur.com/frdEAle.png
developerchat:
  error: '&cYou are not allowed to execute this command. Contact a server administrator
    if you believe this is an error.'
  disable-off: '&3You disabled Developer Chat!'
  disable-on: '&3You enabled Developer Chat'
  toggle-on: '&3You will now send messages in &eDeveloperChat&3!'
  toggle-off: '&3You will no longer send messages in &eDeveloperChat&3!'
  header: '&8[&eDeveloperChat&8]&f '
  placeholder:
    name: '%placeholderyouwant%'
  discordwebhook:
    enabled: false
    webhook: INSERT-WEBHOOK-HERE
    webhookusername: StaffChat Logs
    footer: New Staff Chat message
    footericon: https://i.imgur.com/frdEAle.png
enable-placeholders: false
staffchat-enabled: true
developerchat-enabled: true
adminchat-enabled: true
update-checker: true
